### Create
post http://localhost:3000/user/v1
Content-Type: application/json

{
    "firstname": "Carlos",
    "lastname": "Gonzalez",
    "email": "carlos3.gonzales@email.com",
    "password": "ElGigante2023#",
    "roles": [1,2]
}

### Update
put http://localhost:3000/user/v1/17
Content-Type: application/json

{
    "firstname": "Juan"

}